data:
  train_urls:
    - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/pubmed-sharded-neox/"
  tokenizer: "EleutherAI/gpt-neox-20b"
initialize_from_hf: "mosaicml/mpt-7b@68e1a8e0ebb9b30f3c45c1ef6195980f29063ae2"
lora:
  r: 32
  alpha: 32.0
  target_modules: ["Wqkv"]
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["mpt", "lora", "pubmed"]

  mp: p=f32,c=bfloat16

  model_axis_size: 1
  per_device_parallelism: 4
  per_device_eval_parallelism: 4

  train_batch_size: 1024
  num_train_steps: 1000
  steps_per_eval: 50
optimizer:
  learning_rate: 1.2e-3
  weight_decay: 0.1
